### ISSUE TITLE
more_get_token中key值获取

### ISSUE THREAD

**Issue by iambyd** [zhaoboy9692/qccspider#1]
已关注“小白技术社”，留言机器人回复，相关内容无用

**Comment by xugongli** [comment]
这个不算爬虫，就是调用企查查的接口获取数据，然后解析返回的json数据。

**Comment by zhaoboy9692** [comment]
机器人目前出现问题，都是由我在回复。在app里面抓取数据，可以称之为爬虫，不知道您认为什么才算是爬虫呢？

**Comment by xugongli** [comment]
我说这个不算爬虫，从爬虫的定义来说是说错了的，抱歉。
不过你的这个企查查spider其实是使用了企查查的api接口，我建议你在readme里说明具体是使用到哪个接口，如何申请key，避免大家走弯路，毕竟既然分享出来就是让大家使用的。

不过一般而言，具体就企查查的平台而言，一般是可以突破企查查的反爬策略而拿到数据的，才是真正的爬虫程序.

**Comment by iambyd** [comment]
您好，我这边是想请教下你们key值如何取到，关注“小白技术社”公众号，机器人回复的内容无用，是一些闲聊内容，不是正确回答

**Comment by zhaoboy9692** [comment]
> 您好，我这边是想请教下你们关键值如何取到，关注“小白技术社”公众号，机器人回复的内容无用，是一些闲聊内容，不是正确回答
我在后台看到会回复您的
